#!/bin/bash
CHECK=`ps aux | pgrep mysql | wc -l`
CTL=0
SLEEPTIME=5
until [ $CTL -eq 1 ]
do 
	if [ `ps aux | pgrep mysql | wc -l` -gt 0 ] ; then
		logger "Mysql is runing"
		sleep $SLEEPTIME
	elif [ `ps aux | pgrep mysql | wc -l` -eq 0 ] ; then
		logger "Mysql failed and keepalived dowm,restart Mysql "
		/etc/init.d/mysqld restart 2&1 >/dev/null
		sleep $SLEEPTIME
		if [ `ps aux | pgrep mysql | wc -l` -gt 0 ] ; then
			logger "Mysql restarted,restart keepalived"
			/etc/init.d/keepalived restart 2&1 >/dev/null
		fi
	fi

done
